Conf nginx
etalab/annuaire-entreprises.data.gouv.fr pull request #36
Opened 2021-05-20 16:06 UTC by XavierJp

2021-05-20 16:07 UTC, XavierJp commented
@Bernardstanislas qu'en penses tu ? Est ce que je dois intégrer le bloc location au sous bloc `location / {` ?

2021-05-21 08:16 UTC, Bernardstanislas requested changes
Yes comme tu dis je pense qu'il vaut mieux inclure ton ratelimiting dans chacun des blocks location, pas sûr que ça marche en l'état, et moins facile à lire

2021-05-21 08:39 UTC, Bernardstanislas approved these changes

2021-05-21 08:42 UTC, abulte commented
Pas moyen de passer par cette méthode ? https://dokku.com/docs/configuration/nginx/#customizing-via-configuration-files-included-by-the-default-tem

Pour la maintanabilité du fichier de conf par défaut, qui peut changer entre versions de Dokku.

2021-05-21 08:47 UTC, abulte commented
Ce qui serait _vraiment_ cool c'est d'en faire un plugin, un peu comme https://github.com/Aluxian/dokku-nginx-cache

2021-05-21 08:56 UTC, XavierJp commented
@abulte j'ai mis ca dans un conf file, mais je suis pas sur de moi. Notamment la doc dit que le conf fil est inclu dans le "main server {}" est ce que ca va fonctionner si `limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;` est dans le main server ?

2021-05-21 12:46 UTC, merged